import React, { useEffect, useMemo, useState } from "react";
import Button from "../../components/Button";
import { P204_MODEL, findP204ReferencePoint, getP204Category, getP204Steps, loadP204Progress, resetP204Progress, saveP204Progress, selectP204Category, updateP204Progress } from "../../data/tests/p204.mjs";
const box={background:"#101827",border:"1px solid rgba(148,163,184,.18)",borderRadius:12,padding:16,marginBottom:12};
const input={width:"100%",boxSizing:"border-box",background:"#0B1220",color:"#F8FAFC",border:"1px solid rgba(148,163,184,.28)",borderRadius:8,padding:"11px 12px",font:"inherit"};
const muted={color:"#94A3B8",fontSize:13,lineHeight:1.55};
const formatFrequency=value=>value===.01?"10 kHz":value===.5?"500 kHz":`${value} MHz`;
export default function P204Scenario({view="overview",equipment=[],userSteps=[],notes=""}) {
 const [progress,setProgress]=useState(()=>loadP204Progress(localStorage)); const category=getP204Category(progress); const steps=useMemo(()=>getP204Steps(progress,P204_MODEL,userSteps),[progress.selectedCategoryId,userSteps]);
 useEffect(()=>{saveP204Progress(localStorage,progress)},[progress]); const patch=value=>setProgress(p=>updateP204Progress(p,value));
 const choose=id=>{if(progress.selectedCategoryId&&progress.selectedCategoryId!==id&&!window.confirm("Категория испытания изменена. Параметры, зависящие от категории, будут обновлены. Пользовательские заметки и общие данные будут сохранены."))return;setProgress(p=>selectP204Category(p,id));};
 const reset=()=>{if(window.confirm("Будут удалены введённые параметры, выполненные шаги и результаты этого испытания. Пользовательские изменения методики и глобальный каталог оборудования не будут удалены."))setProgress(resetP204Progress(localStorage));};
 const point=category?findP204ReferencePoint(category.id,progress.currentFrequency?.value,progress.currentFrequency?.unit):null;
 const measured=progress.measuredCurrent===""?null:Number(String(progress.measuredCurrent).replace(",","."));
 const levelReached=point?.value!=null&&Number.isFinite(measured)?measured>=point.value:null;
 const Category=()=> <section style={box}><h3 style={{marginTop:0}}>Категория испытания</h3><div style={{display:"flex",gap:8,flexWrap:"wrap"}}>{P204_MODEL.categories.map(c=><Button key={c.id} variant={category?.id===c.id?"primary":"secondary"} onClick={()=>choose(c.id)}>{c.label}</Button>)}</div><p style={{...muted,marginBottom:0}}>{P204_MODEL.categoryNote}</p></section>;
 const Prompt=()=>!category?<div style={{...box,...muted,padding:12}}>Выберите категорию M, O, R, S, T, W или Y.</div>:null;
 const Parameters=()=> category&&<section style={box}><h3 style={{marginTop:0}}>Параметры испытания</h3><div style={{display:"grid",gridTemplateColumns:"repeat(auto-fit,minmax(210px,1fr))",gap:12}}>{[["Метод",P204_MODEL.method],["Диапазон",P204_MODEL.range.display],["Контролируемая величина",P204_MODEL.controlledQuantity],["Категория",category.id],["Уровень","зависит от частоты и выбранной категории"]].map(([label,value])=><div key={label}><div style={muted}>{label}</div><b>{value}</b></div>)}</div></section>;
 const Levels=()=>category&&<section style={box}><h3 style={{marginTop:0}}>Опорные значения категории {category.id}</h3><div style={{overflowX:"auto"}}><table style={{width:"100%",borderCollapse:"collapse"}}><thead><tr><th style={{textAlign:"left",padding:8}}>Частота</th><th style={{textAlign:"left",padding:8}}>Требуемый ток</th></tr></thead><tbody>{category.referencePoints.map(p=><tr key={p.frequencyMHz} style={{borderTop:"1px solid rgba(148,163,184,.18)"}}><td style={{padding:8}}>{formatFrequency(p.frequencyMHz)}</td><td style={{padding:8}}>{p.curveDefined?"По кривой":`${p.value} mA`}</td></tr>)}</tbody></table></div><p style={muted}>Показаны только подтверждённые опорные точки; промежуточные значения автоматически не интерполируются.</p></section>;
 const Equipment=()=> category&&<section style={box}><h3 style={{marginTop:0}}>Оборудование</h3>{category.requiredEquipmentRoles.map(role=><label key={role.id} style={{display:"block",marginBottom:12}}><b>{role.label}</b><select style={{...input,marginTop:6}} value={progress.equipmentAssignments[role.id]||""} onChange={e=>patch({equipmentAssignments:{...progress.equipmentAssignments,[role.id]:e.target.value}})}><option value="">Не выбрано из каталога</option>{equipment.map(item=><option key={item.id} value={item.id}>{item.name}</option>)}</select></label>)}</section>;
 const Measurements=()=>category&&<section style={box}><h3 style={{marginTop:0}}>Текущая точка испытания</h3><div style={{display:"grid",gridTemplateColumns:"minmax(160px,1fr) 110px minmax(180px,1fr)",gap:8,alignItems:"end"}}><label>Текущая частота<input aria-label="Текущая частота" inputMode="decimal" style={{...input,marginTop:5}} value={progress.currentFrequency?.value||""} onChange={e=>patch({currentFrequency:{...progress.currentFrequency,value:e.target.value}})}/></label><select aria-label="Единица частоты" style={input} value={progress.currentFrequency?.unit||"MHz"} onChange={e=>patch({currentFrequency:{...progress.currentFrequency,unit:e.target.value}})}><option>kHz</option><option>MHz</option><option>GHz</option></select><label>Измеренный наведённый ток<input aria-label="Измеренный наведённый ток" inputMode="decimal" style={{...input,marginTop:5}} value={progress.measuredCurrent} onChange={e=>patch({measuredCurrent:e.target.value})} placeholder="mA"/></label></div><div style={{marginTop:12}}><b>Требуемый: </b>{point?.curveDefined?`уровень определяется по кривой категории ${category.id}`:point?`${point.value} mA`:"для этой частоты требуется значение по нормативной кривой"}<br/><b>Фактический: </b>{Number.isFinite(measured)?`${measured} mA`:"не введён"}{levelReached!==null&&<div style={{marginTop:6,color:levelReached?"#4ADE80":"#FCA5A5"}}>{levelReached?"Уровень достигнут":"Требуемый уровень не достигнут"}</div>}<p style={muted}>Достижение уровня не является автоматическим заключением о соответствии ИРИ.</p></div></section>;
 const Observations=()=> <section style={box}><h3 style={{marginTop:0}}>Состояние ИРИ</h3><div style={{display:"flex",gap:8,flexWrap:"wrap",marginBottom:12}}>{[["normal","Норма"],["deviation","Отклонение"],["not-assessed","Не оценено"]].map(([id,label])=><Button key={id} variant={progress.eutState===id?"primary":"secondary"} onClick={()=>patch({eutState:id})}>{label}</Button>)}</div><label>Комментарий<textarea style={{...input,minHeight:70,marginTop:5}} value={progress.eutComment} onChange={e=>patch({eutComment:e.target.value})}/></label>{progress.eutState==="deviation"&&<Button onClick={()=>patch({deviationEvents:[...progress.deviationEvents,{id:Date.now(),frequency:{...progress.currentFrequency},measuredCurrent:progress.measuredCurrent,effect:progress.eutComment}]})}>Зафиксировать отклонение</Button>}{progress.deviationEvents.length>0&&<div style={{marginTop:12}}>{progress.deviationEvents.map(event=><div key={event.id} style={{...muted,marginTop:5}}>{event.frequency.value} {event.frequency.unit}; {event.measuredCurrent||"—"} mA — {event.effect||"без описания"}</div>)}</div>}</section>;
 const Result=()=> <section style={box}><h3 style={{marginTop:0}}>Результат испытания</h3><select style={input} value={progress.result} onChange={e=>patch({result:e.target.value})}><option value="incomplete">Не завершено</option><option value="pass">Соответствует</option><option value="fail">Не соответствует</option><option value="review">Требуется оценка</option></select><p style={muted}>Итог выбирает инженер по работоспособности и критериям испытания.</p></section>;
 if(view==="steps")return <>{!category?<><Category/><Prompt/></>:<section style={box}><div style={muted}>Шаг {Math.min(progress.currentStep+1,steps.length)} из {steps.length}</div><h3>{steps[progress.currentStep]?.phase||"Проведение"}</h3><p>{steps[progress.currentStep]?.text}</p><div style={{display:"flex",gap:8}}><Button variant="secondary" disabled={!progress.currentStep} onClick={()=>patch({currentStep:Math.max(0,progress.currentStep-1)})}>Назад</Button><Button onClick={()=>patch({completedSteps:{...progress.completedSteps,[steps[progress.currentStep].id]:true},currentStep:Math.min(steps.length-1,progress.currentStep+1)})}>Выполнено / Далее</Button></div></section>}</>;
 if(view==="before")return <><Category/>{category?<section style={box}><h3 style={{marginTop:0}}>Подготовка</h3>{category.preparationSteps.map(item=><label key={item.id} style={{display:"block",padding:7}}><input type="checkbox" checked={!!progress.checklist[item.id]} onChange={e=>patch({checklist:{...progress.checklist,[item.id]:e.target.checked}})}/> {item.text}</label>)}</section>:<Prompt/>}</>;
 if(view==="during")return <>{category?<><Parameters/><Measurements/><Observations/></>:<Prompt/>}</>; if(view==="after")return <><Result/><Button variant="danger" onClick={reset}>Сбросить прогресс испытания</Button></>; if(view==="schema")return <>{category?<Equipment/>:<Prompt/>}</>;
 return <><div style={box}><h2 style={{marginTop:0}}>{P204_MODEL.title}</h2><p style={{marginBottom:0}}>{P204_MODEL.description}</p></div><Category/>{category?<><Parameters/><Levels/><Equipment/></>:<Prompt/>}<Result/><div style={muted}>Пользовательские заметки хранятся отдельно и сохраняются при смене категории{notes?": сохранены":""}.</div></>;
}
