import React, { useEffect, useMemo, useState } from "react";
import Button from "../../components/Button";
import { P204_MODEL, getP204Category, getP204Steps, loadP204Progress, resetP204Progress, saveP204Progress, selectP204Category, updateP204Progress } from "../../data/tests/p204.mjs";
const box={background:"#101827",border:"1px solid rgba(148,163,184,.18)",borderRadius:12,padding:16,marginBottom:12};
const input={width:"100%",boxSizing:"border-box",background:"#0B1220",color:"#F8FAFC",border:"1px solid rgba(148,163,184,.28)",borderRadius:8,padding:"11px 12px",font:"inherit"};
const muted={color:"#94A3B8",fontSize:13,lineHeight:1.55};
export default function P204Scenario({view="overview",equipment=[],userSteps=[],notes=""}) {
 const [progress,setProgress]=useState(()=>loadP204Progress(localStorage)); const category=getP204Category(progress); const steps=useMemo(()=>getP204Steps(progress,P204_MODEL,userSteps),[progress.selectedCategoryId,userSteps]);
 useEffect(()=>{saveP204Progress(localStorage,progress)},[progress]); const patch=value=>setProgress(p=>updateP204Progress(p,value));
 const choose=id=>{if(progress.selectedCategoryId&&progress.selectedCategoryId!==id&&!window.confirm("Категория испытания изменена. Параметры, зависящие от категории, будут обновлены. Пользовательские заметки и общие данные будут сохранены."))return;setProgress(p=>selectP204Category(p,id));};
 const reset=()=>{if(window.confirm("Будут удалены введённые параметры, выполненные шаги и результаты этого испытания. Пользовательские изменения методики и глобальный каталог оборудования не будут удалены."))setProgress(resetP204Progress(localStorage));};
 const Category=()=> <section style={box}><h3 style={{marginTop:0}}>Категория испытания</h3>{P204_MODEL.categories.length?<select aria-label="Категория испытания" style={input} value={progress.selectedCategoryId||""} onChange={e=>choose(e.target.value)}><option value="">Выберите категорию</option>{P204_MODEL.categories.map(c=><option key={c.id} value={c.id}>{c.label}</option>)}</select>:<><p style={muted}>Категории пока не заполнены в нормативной базе.</p><p style={muted}>Выберите категорию испытания, чтобы сформировать параметры, оборудование и последовательность проведения.</p></>}</section>;
 const Empty=({children="Сначала выберите категорию испытания."})=><div style={{...box,...muted}}>{children}</div>;
 const Parameters=()=> <section style={box}><h3 style={{marginTop:0}}>Параметры испытания</h3>{!category?<p style={muted}>Сначала выберите категорию испытания.</p>:!(category.parameters||[]).length?<p style={muted}>Нормативные параметры для этой категории пока не заполнены.</p>:(category.parameters||[]).map(p=><div key={p.id} style={{marginBottom:12}}><b>{p.label}</b>{p.input?<input type="number" style={{...input,marginTop:6}} value={progress.userValues[p.id]?.value||""} onChange={e=>patch({userValues:{...progress.userValues,[p.id]:{value:e.target.value,unit:p.unit||"",source:"user"}}})}/>:<div>{p.value??"Не задано"} {p.unit||""}</div>}<small style={muted}>Источник: {p.source||"Требуется нормативное значение"}</small></div>)}</section>;
 const Equipment=()=> <section style={box}><h3 style={{marginTop:0}}>Оборудование</h3>{!category?<p style={muted}>Назначьте оборудование для проведения испытания после выбора категории.</p>:!(category.requiredEquipmentRoles||[]).length?<p style={muted}>Требования к ролям оборудования пока не заданы.</p>:category.requiredEquipmentRoles.map(role=><label key={role.id} style={{display:"block",marginBottom:12}}><b>Требуется методикой: {role.label}</b><select style={{...input,marginTop:6}} value={progress.equipmentAssignments[role.id]||""} onChange={e=>patch({equipmentAssignments:{...progress.equipmentAssignments,[role.id]:e.target.value}})}><option value="">Не выбрано</option>{equipment.map(item=><option key={item.id} value={item.id}>{item.name}</option>)}</select></label>)}</section>;
 const Observations=()=> <section style={box}><h3 style={{marginTop:0}}>Состояние изделия</h3>{[["initial","Исходное состояние"],["during","Состояние во время воздействия"],["deviation","Обнаруженное отклонение"],["comment","Комментарий"]].map(([id,label])=><label key={id} style={{display:"block",marginBottom:10}}>{label}<textarea style={{...input,minHeight:62,marginTop:5}} value={progress.observations[id]} onChange={e=>patch({observations:{...progress.observations,[id]:e.target.value}})}/></label>)}</section>;
 const Result=()=> <section style={box}><h3 style={{marginTop:0}}>Результат испытания</h3><select style={input} value={progress.result} onChange={e=>patch({result:e.target.value})}><option value="incomplete">Не завершено</option><option value="pass">Соответствует</option><option value="fail">Не соответствует</option><option value="review">Требуется оценка</option></select><p style={muted}>Итог выбирает инженер; автоматическая нормативная оценка не применяется.</p></section>;
 if(view==="steps")return <>{!category?<><Category/><Empty/></>:!steps.length?<Empty>Шаги для выбранной категории пока не заполнены.</Empty>:<section style={box}><div style={muted}>Шаг {Math.min(progress.currentStep+1,steps.length)} из {steps.length}</div><h3>{steps[progress.currentStep]?.phase||"Проведение"}</h3><p>{steps[progress.currentStep]?.text}</p><div style={{display:"flex",gap:8,flexWrap:"wrap"}}><Button variant="secondary" disabled={!progress.currentStep} onClick={()=>patch({currentStep:Math.max(0,progress.currentStep-1)})}>Назад</Button><Button onClick={()=>patch({completedSteps:{...progress.completedSteps,[steps[progress.currentStep].id]:true},currentStep:Math.min(steps.length-1,progress.currentStep+1)})}>Выполнено / Далее</Button></div></section>}</>;
 if(view==="before")return <><Category/>{!category?<Empty/>:<section style={box}><h3 style={{marginTop:0}}>Подготовка</h3>{(category.preparationSteps||[]).length?category.preparationSteps.map(item=><label key={item.id} style={{display:"block",padding:7}}><input type="checkbox" checked={!!progress.checklist[item.id]} onChange={e=>patch({checklist:{...progress.checklist,[item.id]:e.target.checked}})}/> {item.text}</label>):<p style={muted}>Пункты подготовки для категории пока не заполнены.</p>}</section>}</>;
 if(view==="during")return <>{!category?<Empty/>:<><Parameters/><Observations/></>}</>; if(view==="after")return <><Result/><Button variant="danger" onClick={reset}>Сбросить прогресс испытания</Button></>; if(view==="schema")return <>{category&&(category.requiredEquipmentRoles||[]).length?<Equipment/>:<Empty>Назначения приборов появятся здесь после заполнения нормативных ролей и выбора категории.</Empty>}</>;
 return <><Category/><Parameters/><Equipment/><div style={{...muted,marginBottom:12}}>Автоматический расчёт для этого параметра пока недоступен.</div><Result/><div style={muted}>Пользовательские заметки хранятся отдельно и сохраняются при смене категории{notes?": сохранены":""}.</div></>;
}
