import React, { useMemo, useRef, useState } from "react";
import { CALIBRATION_STORAGE_KEY, FREQUENCY_UNITS, createCalibrationPoint, createCalibrationSet, exportCalibrationCsv, exportCalibrationJson, findCalibrationPoint, importCalibrationCsv, loadCalibrationSets, parseCalibrationCsv, saveCalibrationSets, sortCalibrationPoints, calculateCorrectedValue } from "../../data/calibration.mjs";

const box={background:"#101827",border:"1px solid rgba(148,163,184,.18)",borderRadius:14,padding:16,marginBottom:12};
const input={width:"100%",boxSizing:"border-box",padding:"9px 10px",borderRadius:8,border:"1px solid rgba(148,163,184,.3)",background:"#0B1220",color:"#F8FAFC"};
const button={padding:"9px 13px",border:0,borderRadius:9,background:"#2563EB",color:"white",fontWeight:700,cursor:"pointer"};
const emptySet={name:"",testType:"21.5",laboratory:"",workplace:"",pathDescription:"",measurementDistance:"",calibrationDate:"",note:"",equipmentIds:[]};
const emptyPoint={frequency:"",frequencyUnit:"MHz",correction:"",correctionUnit:"dB",comment:"",antennaFactor:"",cableLoss:"",preamplifierFactor:"",lisnCorrection:"",currentProbeFactor:""};
const fields={frequency:"Частота",correction:"Итоговая поправка",antennaFactor:"Коэффициент антенны",cableLoss:"Потери кабеля",preamplifierFactor:"Предусилитель",lisnCorrection:"Поправка LISN",currentProbeFactor:"Токовый пробник",comment:"Комментарий"};
const download=(name,data,type)=>{const url=URL.createObjectURL(new Blob([data],{type}));const a=document.createElement("a");a.href=url;a.download=name;a.click();URL.revokeObjectURL(url)};

export default function CalibrationManager({ equipment = [], initialTestType = null, onClose }) {
  const activeTestType=initialTestType||"21.5";
  const [sets,setSets]=useState(()=>loadCalibrationSets(localStorage)); const [selectedId,setSelectedId]=useState(null);
  const [draft,setDraft]=useState(()=>({...emptySet,testType:activeTestType})); const [creating,setCreating]=useState(false);
  const visibleSets=sets.filter(x=>x.testType===activeTestType);
  const selected=visibleSets.find(x=>x.id===selectedId); const persist=next=>{setSets(next);saveCalibrationSets(localStorage,next)};
  const saveSet=()=>{try{const value=createCalibrationSet(draft);persist([...sets,value]);setSelectedId(value.id);setCreating(false)}catch(e){alert(e.message)}};
  if(selected) return <SetEditor set={selected} equipment={equipment} onBack={()=>setSelectedId(null)} onChange={value=>persist(sets.map(x=>x.id===value.id?value:x))} onDelete={()=>{if(confirm("Удалить набор без возможности восстановления?")){persist(sets.filter(x=>x.id!==selected.id));setSelectedId(null)}}}/>;
  return <div><div style={{display:"flex",justifyContent:"space-between",alignItems:"center",gap:10,marginBottom:14}}><div><h2 style={{margin:0}}>Калибровка измерительного тракта</h2><div style={{color:"#94A3B8",fontSize:13}}>Раздел 21 → Калибровка → Наборы</div></div>{onClose&&<button style={button} onClick={onClose}>Назад</button>}</div>
    <div style={{...box,borderLeft:"3px solid #F59E0B",color:"#CBD5E1",fontSize:13}}>Здесь хранятся рабочие данные конкретной лаборатории и тракта. Нормативные пределы и универсальные коэффициенты не предзаполняются.</div>
    <div style={{display:"flex",justifyContent:"space-between",alignItems:"center",marginBottom:12}}><b>п.{activeTestType} · {visibleSets.length} наборов · {visibleSets.reduce((n,x)=>n+x.points.length,0)} точек</b><button style={button} onClick={()=>setCreating(true)}>+ Создать набор</button></div>
    {creating&&<div style={box}><h3>Новый набор п.{activeTestType}</h3><SetFields draft={draft} setDraft={setDraft} equipment={equipment} lockTestType/><div style={{display:"flex",gap:8}}><button style={button} onClick={saveSet}>Сохранить</button><button style={{...button,background:"#334155"}} onClick={()=>setCreating(false)}>Отмена</button></div></div>}
    {visibleSets.map(s=><button key={s.id} onClick={()=>setSelectedId(s.id)} style={{...box,width:"100%",display:"grid",gridTemplateColumns:"1fr auto",textAlign:"left",color:"#F8FAFC",cursor:"pointer"}}><span><b>{s.name}</b><small style={{display:"block",color:"#94A3B8",marginTop:5}}>п.{s.testType} · {s.workplace||"стенд не указан"} · калибровка {s.calibrationDate||"дата не указана"}</small></span><b>{s.points.length} точек{s.status==="archived"?" · архив":""}</b></button>)}
    {!visibleSets.length&&!creating&&<div style={{...box,textAlign:"center",color:"#94A3B8"}}>Наборов п.{activeTestType} пока нет. Создайте пустой набор или импортируйте CSV после создания.</div>}
  </div>;
}

function SetFields({draft,setDraft,equipment,lockTestType=false}) { const set=(k,v)=>setDraft(x=>({...x,[k]:v})); return <div style={{display:"grid",gridTemplateColumns:"repeat(auto-fit,minmax(220px,1fr))",gap:10,marginBottom:14}}>
  {[['name','Название'],['laboratory','Лаборатория'],['workplace','Стенд / рабочее место'],['pathDescription','Описание тракта'],['measurementDistance','Расстояние измерения'],['calibrationDate','Дата калибровки'],['note','Примечание']].map(([k,l])=><label key={k}><small>{l}</small><input type={k==='calibrationDate'?'date':'text'} style={input} value={draft[k]||""} onChange={e=>set(k,e.target.value)}/></label>)}
  <label><small>Тип испытания</small><select disabled={lockTestType} style={input} value={draft.testType} onChange={e=>set('testType',e.target.value)}><option>21.4</option><option>21.5</option></select></label>
  <label><small>Связанное оборудование</small><select multiple style={{...input,minHeight:92}} value={draft.equipmentIds||[]} onChange={e=>set('equipmentIds',[...e.target.selectedOptions].map(o=>o.value))}>{equipment.map(e=><option key={e.id} value={e.id}>{e.name} · {e.arm||"без стенда"}</option>)}</select></label>
  </div> }

function SetEditor({set,equipment,onBack,onChange,onDelete}) { const [q,setQ]=useState("");const [sort,setSort]=useState("asc");const [point,setPoint]=useState(emptyPoint);const [editing,setEditing]=useState(null);const [selected,setSelected]=useState([]);const [csv,setCsv]=useState(null);const [result,setResult]=useState(null);const file=useRef();
  const update=patch=>onChange({...set,...patch,updatedAt:new Date().toISOString()});
  const visible=useMemo(()=>sortCalibrationPoints(set.points,sort).filter(p=>!q||String(p.frequency).includes(q)||p.comment.toLowerCase().includes(q.toLowerCase())).slice(0,200),[set.points,q,sort]);
  const savePoint=()=>{try{const p=createCalibrationPoint(point,set.points.length);update({points:editing?set.points.map(x=>x.id===editing?p:x):[...set.points,p]});setPoint(emptyPoint);setEditing(null)}catch(e){alert(e.message)}};
  const startEdit=p=>{setEditing(p.id);setPoint({...p})}; const duplicate=p=>update({points:[...set.points,createCalibrationPoint({...p,id:"",order:set.points.length+1},set.points.length)]});
  return <div><button style={{...button,background:"#334155",marginBottom:10}} onClick={onBack}>← Наборы</button><div style={box}><h2 style={{marginTop:0}}>{set.name}</h2><SetFields draft={set} setDraft={x=>update(typeof x==='function'?x(set):x)} equipment={equipment} lockTestType/><div style={{display:"flex",gap:8,flexWrap:"wrap"}}><button style={button} onClick={()=>update({status:set.status==='active'?'archived':'active'})}>{set.status==='active'?'Архивировать':'Вернуть в работу'}</button><button style={{...button,background:"#334155"}} onClick={()=>download(`${set.name}.csv`,exportCalibrationCsv(set),'text/csv')}>Экспорт CSV</button><button style={{...button,background:"#334155"}} onClick={()=>download(`${set.name}.json`,exportCalibrationJson(set),'application/json')}>JSON backup</button><button style={{...button,background:"#DC2626"}} onClick={onDelete}>Удалить набор</button></div></div>
    <Measurement set={set}/><div style={box}><h3>Добавить / редактировать точку</h3><div style={{display:"grid",gridTemplateColumns:"repeat(auto-fit,minmax(145px,1fr))",gap:8}}>{Object.entries(fields).map(([k,l])=><label key={k}><small>{l}</small><input style={input} value={point[k]??""} onChange={e=>setPoint(x=>({...x,[k]:e.target.value}))}/></label>)}<label><small>Единица частоты</small><select style={input} value={point.frequencyUnit} onChange={e=>setPoint(x=>({...x,frequencyUnit:e.target.value}))}>{FREQUENCY_UNITS.map(x=><option key={x}>{x}</option>)}</select></label><label><small>Единица поправки</small><input style={input} value={point.correctionUnit} onChange={e=>setPoint(x=>({...x,correctionUnit:e.target.value}))}/></label></div><button style={{...button,marginTop:10}} onClick={savePoint}>{editing?'Сохранить':'Добавить точку'}</button></div>
    <div style={box}><input ref={file} hidden type="file" accept=".csv,text/csv" onChange={e=>{const r=new FileReader();r.onload=()=>setCsv({parsed:parseCalibrationCsv(r.result),mapping:{frequency:0,correction:1},frequencyUnit:'MHz',correctionUnit:'dB'});r.readAsText(e.target.files[0]);e.target.value=""}}/><button style={button} onClick={()=>file.current.click()}>Импортировать CSV</button>{csv&&<CsvImport value={csv} setValue={setCsv} onImport={()=>{const r=importCalibrationCsv(csv.parsed,csv.mapping,csv);update({points:[...set.points,...r.points]});setResult(r);setCsv(null)}}/>}{result&&<p>Импортировано: {result.imported} · пропущено: {result.skipped} · ошибок: {result.errorCount}</p>}</div>
    <div style={box}><div style={{display:"flex",gap:8,flexWrap:"wrap",alignItems:"center"}}><input style={{...input,maxWidth:280}} placeholder="Поиск по частоте / комментарию" value={q} onChange={e=>setQ(e.target.value)}/><button style={{...button,background:"#334155"}} onClick={()=>setSort(sort==='asc'?'desc':'asc')}>Сортировка {sort==='asc'?'↑':'↓'}</button><b>{set.points.length} точек</b>{selected.length>0&&<button style={{...button,background:'#DC2626'}} onClick={()=>{update({points:set.points.filter(p=>!selected.includes(p.id))});setSelected([])}}>Удалить выбранные ({selected.length})</button>}</div><small style={{color:'#94A3B8'}}>Для производительности показаны первые 200 совпадений. Используйте поиск для быстрого перемещения.</small><div style={{overflowX:'auto',maxHeight:520}}><table style={{width:'100%',borderCollapse:'collapse',marginTop:10}}><thead><tr>{['','№','Частота','Поправка','Комментарий',''].map((x,i)=><th key={i} style={{textAlign:'left',padding:8}}>{x}</th>)}</tr></thead><tbody>{visible.map(p=><tr key={p.id} style={{borderTop:'1px solid #334155'}}><td><input type="checkbox" checked={selected.includes(p.id)} onChange={()=>setSelected(x=>x.includes(p.id)?x.filter(id=>id!==p.id):[...x,p.id])}/></td><td>{p.order}</td><td>{p.frequency} {p.frequencyUnit}</td><td>{p.correction} {p.correctionUnit}</td><td>{p.comment}</td><td><button style={button} onClick={()=>startEdit(p)}>Изменить</button> <button style={{...button,background:'#334155'}} onClick={()=>duplicate(p)}>Дублировать</button> <button style={{...button,background:'#DC2626'}} onClick={()=>update({points:set.points.filter(x=>x.id!==p.id)})}>Удалить</button></td></tr>)}</tbody></table></div></div>
  </div> }

function CsvImport({value,setValue,onImport}) {const set=(k,v)=>setValue(x=>({...x,[k]:v}));return <div style={{marginTop:12}}><h4>Предпросмотр и сопоставление колонок</h4><div style={{display:'grid',gridTemplateColumns:'repeat(auto-fit,minmax(180px,1fr))',gap:8}}>{Object.entries(fields).map(([k,l])=><label key={k}><small>{l}</small><select style={input} value={value.mapping[k]??''} onChange={e=>set('mapping',{...value.mapping,[k]:e.target.value===''?undefined:Number(e.target.value)})}><option value="">Не импортировать</option>{value.parsed.headers.map((h,i)=><option key={i} value={i}>{h||`Колонка ${i+1}`}</option>)}</select></label>)}</div><div style={{display:'flex',gap:8,margin:'10px 0'}}><select style={{...input,maxWidth:120}} value={value.frequencyUnit} onChange={e=>set('frequencyUnit',e.target.value)}>{FREQUENCY_UNITS.map(x=><option key={x}>{x}</option>)}</select><input style={{...input,maxWidth:150}} value={value.correctionUnit} onChange={e=>set('correctionUnit',e.target.value)}/><button style={button} onClick={onImport}>Импортировать</button></div><div style={{overflow:'auto',maxHeight:240}}><table><tbody>{[value.parsed.headers,...value.parsed.rows.slice(0,20)].map((r,i)=><tr key={i}>{r.map((c,j)=><td key={j} style={{padding:5,border:'1px solid #334155'}}>{c}</td>)}</tr>)}</tbody></table></div></div>}

function Measurement({set}) {const [frequency,setFrequency]=useState('');const [unit,setUnit]=useState('MHz');const [measured,setMeasured]=useState('');const [valueUnit,setValueUnit]=useState('dBµV');const [limit,setLimit]=useState('');const point=findCalibrationPoint(set,frequency,unit);const r=point?calculateCorrectedValue({measured,measuredUnit:valueUnit,correction:point.correction,correctionUnit:point.correctionUnit,limit}):null;return <div style={box}><h3>Использование при испытании п.{set.testType}</h3><div style={{display:'grid',gridTemplateColumns:'repeat(auto-fit,minmax(150px,1fr))',gap:8}}><input style={input} placeholder="Частота" value={frequency} onChange={e=>setFrequency(e.target.value)}/><select style={input} value={unit} onChange={e=>setUnit(e.target.value)}>{FREQUENCY_UNITS.map(x=><option key={x}>{x}</option>)}</select><input style={input} placeholder="Измеренное значение" value={measured} onChange={e=>setMeasured(e.target.value)}/><input style={input} placeholder="Единица" value={valueUnit} onChange={e=>setValueUnit(e.target.value)}/><input style={input} placeholder="Предел (необязательно)" value={limit} onChange={e=>setLimit(e.target.value)}/></div>{frequency&&!point&&<p style={{color:'#F59E0B'}}>Калибровочная точка для этой частоты отсутствует. Автоматическая интерполяция не выполняется.</p>}{point&&<p>Измерено: <b>{measured||'—'} {valueUnit}</b> · поправка: <b>{point.correction} {point.correctionUnit}</b> · скорректировано: <b>{r?.compatible?r.corrected:'автоматический расчёт для этой комбинации единиц не настроен'} {r?.compatible?valueUnit:''}</b>{r?.margin!==null&&<> · запас / превышение: <b>{r.margin}</b></>}</p>}</div>}

export { CALIBRATION_STORAGE_KEY };
