import React, { useEffect, useMemo, useState } from "react";
import { readExistingEquipment, loadProgress, saveProgress } from "./persistence.mjs";
import { equipmentOptionLabels } from "./engine.mjs";
import { SECTION_16_PROFILE } from "./section16/profiles.mjs";
import { applicableSection16Procedures } from "./section16/applicability.mjs";
import { AUTOMATION_SYSTEMS, automationSystemById, executionPlan, verifiedForProcedure } from "./section16/executionAdapters.mjs";
import { createSection16Result, SECTION_16_SCENARIO_ID } from "./section16/state.mjs";
import "./guidedTest.css";

const steps = ["Определите питание", "Проверьте план", "Выберите способ", "Подготовьте установку", "Выполните процедуры", "Результат"];
const empty = { inputs: {}, configuration: {}, equipment: {}, parameters: {}, conditions: {}, measurements: {}, procedureResults: {}, currentProcedure: 0, executionMode: "" };
const Field = ({ label, children, hint }) => <label>{label}{children}{hint && <small>{hint}</small>}</label>;

export default function Section16GuidedTest({ onBackToSelection, onOpenEquipment = () => {} }) {
  const [progress, setProgress] = useState(() => ({ ...empty, ...loadProgress(localStorage, SECTION_16_SCENARIO_ID) }));
  const stage = Math.min(progress.currentStage || 0, steps.length - 1);
  const patch = value => setProgress(old => ({ ...old, ...value }));
  useEffect(() => { saveProgress(localStorage, SECTION_16_SCENARIO_ID, progress); }, [progress]);
  const configuration = progress.configuration || {};
  const procedures = useMemo(() => applicableSection16Procedures(configuration, SECTION_16_PROFILE), [configuration]);
  const procedureIndex = Math.min(progress.currentProcedure || 0, Math.max(procedures.length - 1, 0));
  const procedure = procedures[procedureIndex];
  const system = automationSystemById(progress.automationSystemId);
  const plan = executionPlan(procedure, progress.executionMode, system);
  const equipment = useMemo(() => readExistingEquipment(localStorage, []), []);
  const equipmentLabels = equipmentOptionLabels(equipment);
  const updateConfig = value => patch({ configuration: { ...configuration, ...value } });
  const updateInput = (id, value) => patch({ inputs: { ...progress.inputs, [id]: value } });
  const canContinue = [Boolean(configuration.powerType && configuration.nominalVoltage), procedures.length > 0, Boolean(progress.executionMode && (progress.executionMode === "manual" || progress.automationSystemId)), true, procedures.every(item => progress.procedureResults?.[item.id]), false][stage];
  const go = next => patch({ currentStage: Math.max(0, Math.min(next, steps.length - 1)) });
  const result = stage === 5 ? createSection16Result(progress, SECTION_16_PROFILE, procedures) : null;

  return <main className="guided-runner section16-runner">
    <button className="back-selection" onClick={onBackToSelection}>← Вернуться к выбору испытания</button>
    <header className="guided-header"><div><span className="guided-kicker">Раздел 16 · Guided Test</span><h1>Восприимчивость по входу электропитания</h1><p>Toolkit строит маршрут по конфигурации питания и ведёт инженера по применимым воздействиям.</p></div><div className="guided-progress"><b>Шаг {stage + 1} из {steps.length}</b><progress value={stage + 1} max={steps.length}/></div></header>
    <nav className="stage-list" aria-label="Этапы испытания">{steps.map((title, index) => <button key={title} className={index === stage ? "active" : ""} disabled={index > stage} onClick={() => go(index)}><span>{index + 1}</span>{title}</button>)}</nav>
    <article className="guided-stage">
      {stage === 0 && <><h2>Определите питание изделия</h2><p className="stage-intro">Укажите фактическую конфигурацию изделия. Toolkit сам построит последовательность испытаний.</p>
        <Field label="Изделие"><input value={progress.inputs.eutName || ""} onChange={e => updateInput("eutName", e.target.value)} placeholder="Наименование изделия"/></Field>
        <fieldset className="guided-field radio-field"><legend>Тип питания</legend>{[["DC", "Постоянный ток (DC)"], ["AC", "Переменный ток (AC)"]].map(([value, label]) => <label className="radio-option" key={value}><input type="radio" checked={configuration.powerType === value} onChange={() => updateConfig({ powerType: value, frequency: "", phase: "" })}/>{label}</label>)}</fieldset>
        {configuration.powerType && <div className="guided-panel"><Field label="Номинальное напряжение, В" hint="Фактическое значение изделия; это не универсальная уставка Section 16."><input inputMode="decimal" value={configuration.nominalVoltage || ""} onChange={e => updateConfig({ nominalVoltage: e.target.value })}/></Field>
          {configuration.powerType === "DC" ? <Field label="Номинальный класс профиля" hint="Список классов появится после подтверждения нормативного профиля."><select disabled><option>Требует подтверждённого профиля</option></select></Field> : <><Field label="Частота сети, Гц"><input inputMode="decimal" value={configuration.frequency || ""} onChange={e => updateConfig({ frequency: e.target.value })}/></Field><Field label="Сеть"><select value={configuration.phase || ""} onChange={e => updateConfig({ phase: e.target.value })}><option value="">Выберите конфигурацию</option><option value="single">Однофазная</option><option value="three">Трёхфазная</option></select></Field></>}
          <Field label="Категория / дополнительные обозначения" hint="Необязательно; будет использовано правилами подтверждённого профиля."><input value={configuration.category || ""} onChange={e => updateConfig({ category: e.target.value })}/></Field></div>}
        <p className="guided-warning">Нормативные классы, уровни и длительности пока не заполнены: {SECTION_16_PROFILE.TODO}</p></>}
      {stage === 1 && <><h2>Какие испытания необходимо выполнить?</h2><p>Для введённой конфигурации Toolkit сформировал последовательность. Неприменимые процедуры не показаны.</p><ol className="procedure-list">{procedures.map(item => <li key={item.id}><strong>{item.title}</strong><span>Параметры воздействия будут взяты из нормативного профиля.</span></li>)}</ol><p className="guided-warning">Это архитектурный профиль с неподтверждёнными числовыми данными. Перед реальным испытанием профиль должен быть верифицирован по первичному источнику.</p></>}
      {stage === 2 && <><h2>Как выполняется испытание?</h2><fieldset className="guided-field radio-field"><legend>Способ выполнения</legend><label className="radio-option"><input type="radio" checked={progress.executionMode === "manual"} onChange={() => patch({ executionMode: "manual", automationSystemId: "" })}/>Вручную</label><label className="radio-option"><input type="radio" checked={progress.executionMode === "automated"} onChange={() => patch({ executionMode: "automated" })}/>Через ПО / автоматизированный стенд</label></fieldset>
        {progress.executionMode === "automated" && <section className="guided-panel"><h3>Выберите ПО / систему автоматизации</h3><select value={progress.automationSystemId || ""} onChange={e => patch({ automationSystemId: e.target.value })}><option value="">Не выбрано</option>{AUTOMATION_SYSTEMS.map(item => <option key={item.id} value={item.id}>{item.name}</option>)}</select>{system && <p className="guided-notice">Toolkit не приписывает этой системе неподтверждённые возможности. Совместимость с каждой процедурой подтверждает инженер.</p>}<Field label="Название и версия" hint="Для «Другого ПО» или собственного стенда."><input value={progress.customAutomationName || ""} onChange={e => patch({ customAutomationName: e.target.value })}/></Field></section>}</>}
      {stage === 3 && <><h2>Подготовьте установку</h2><section className="instruction"><h3>1. Выберите оборудование из каталога</h3><p>Выберите экземпляр источника или стенда, который создаёт воздействия. Данные каталога не изменяются.</p><select value={progress.equipment.powerSource || ""} onChange={e => patch({ equipment: { ...progress.equipment, powerSource: e.target.value } })}><option value="">Не выбрано</option>{equipment.map(item => <option key={item.id} value={item.id}>{equipmentLabels.get(item.id)}</option>)}</select><button className="guided-link" onClick={onOpenEquipment}>Добавить оборудование в каталог</button></section><section className="instruction"><h3>2. Подключите контроль</h3><p>Подготовьте измерение фактического питания и способ наблюдения за работоспособностью изделия.</p></section><section className="instruction"><h3>3. Проверьте параметры</h3><p>Не начинайте воздействие, пока уровни и длительности не загружены из проверенного нормативного профиля.</p></section></>}
      {stage === 4 && procedure && plan && <><h2>Выполните процедуру</h2><div className="procedure-current"><span>Процедура {procedureIndex + 1} из {procedures.length}</span><strong>{procedure.title}</strong></div>{plan.setup.map((text, i) => <section className="instruction" key={`s${i}`}><h3>Подготовка {i + 1}</h3><p>{text}</p></section>)}<section className="guided-panel"><h3>{progress.executionMode === "manual" ? "Действия инженера" : `Действия с внешней системой: ${system?.name}`}</h3><ol>{plan.actions.map(text => <li key={text}>{text}</li>)}</ol><h3>Что контролировать</h3><ul>{plan.monitoring.map(text => <li key={text}>{text}</li>)}</ul></section>{progress.executionMode === "automated" && <p className="guided-warning">Совместимость: {verifiedForProcedure(system, procedure) ? "есть документированная capability" : "проверьте сценарий стенда самостоятельно"}.</p>}<Field label="Наблюдение / полученный результат"><textarea value={progress.procedureResults?.[procedure.id] || ""} onChange={e => patch({ procedureResults: { ...progress.procedureResults, [procedure.id]: e.target.value } })} placeholder="Что произошло с изделием?"/></Field><div className="procedure-nav"><button disabled={!procedureIndex} onClick={() => patch({ currentProcedure: procedureIndex - 1 })}>Предыдущая процедура</button><button disabled={procedureIndex >= procedures.length - 1 || !progress.procedureResults?.[procedure.id]} onClick={() => patch({ currentProcedure: procedureIndex + 1 })}>Следующая процедура</button></div></>}
      {stage === 5 && result && <><h2>Испытание завершено</h2><section className="guided-panel test-result"><div className="category"><span>Результат сохранён</span><strong>{result.procedures.length}</strong><span>процедур</span></div><dl><dt>Изделие</dt><dd>{result.product.name || "—"}</dd><dt>Питание</dt><dd>{result.configuration.powerType}, {result.configuration.nominalVoltage} В</dd><dt>Нормативный профиль</dt><dd>{SECTION_16_PROFILE.title}</dd><dt>Способ</dt><dd>{result.execution.mode === "manual" ? "Вручную" : "Автоматизированный стенд"}</dd>{system && <><dt>ПО / стенд</dt><dd>{system.name}{progress.customAutomationName ? `: ${progress.customAutomationName}` : ""}</dd></>}<dt>Оборудование</dt><dd>{equipmentLabels.get(progress.equipment.powerSource) || "Не зафиксировано"}</dd></dl></section><p className="guided-warning">Числовые параметры не объявлены подтверждёнными до подключения проверенного нормативного профиля.</p></>}
    </article>
    {stage < 5 && !canContinue && <p className="guided-warning">Заполните данные текущего шага, чтобы продолжить.</p>}
    <footer><button disabled={stage === 0} onClick={() => go(stage - 1)}>Назад</button><button disabled={stage === 5 || !canContinue} onClick={() => go(stage + 1)}>Далее</button></footer>
  </main>;
}
