import React, { useMemo, useState } from "react";
import {
  antennaFactorReceive, antennaFactorTransmit, antennaPositionStep, chamberBeatFrequencyMHz,
  chamberKField, chamberKPower, chamberModesEquivalent, chamberModesRectangular, fieldFromMeasuredVoltage,
  frequencyToHz, shieldingEffectiveness,
} from "../../calculations/engineering.mjs";
import { EMC_LIMITS, evaluateLimit, sampleLimit } from "../../data/limits/emcLimits.mjs";

const S = { card: { background: "#101827", border: "1px solid rgba(148,163,184,.18)", borderRadius: 14, padding: 18 }, input: { width: "100%", boxSizing: "border-box", padding: "10px 12px", borderRadius: 8, border: "1px solid rgba(148,163,184,.25)", background: "#050814", color: "#F8FAFC" } };
const n = value => Number(String(value).replace(",", "."));
const pretty = value => Number.isFinite(value) ? value.toLocaleString("ru-RU", { maximumSignificantDigits: 10 }) : "—";
const Field = ({ label, children }) => <label style={{ display: "grid", gap: 6, minWidth: 0, color: "#94A3B8", fontSize: 12 }}>{label}{children}</label>;
const Grid = ({ children }) => <div style={{ display: "grid", gridTemplateColumns: "repeat(auto-fit,minmax(170px,1fr))", gap: 12, marginBottom: 14 }}>{children}</div>;
const Result = ({ children }) => <div style={{ padding: 13, borderRadius: 9, background: "rgba(37,99,235,.18)", color: "#F8FAFC", lineHeight: 1.7 }}>{children}</div>;
const Actions = ({ calculate, clear }) => <div style={{ display: "flex", gap: 8, margin: "14px 0" }}><button onClick={calculate} style={{ ...S.input, width: "auto", background: "#2563EB", cursor: "pointer", fontWeight: 700 }}>Рассчитать</button><button onClick={clear} style={{ ...S.input, width: "auto", cursor: "pointer" }}>Очистить</button></div>;
const Tabs = ({ tabs, active, setActive }) => <div style={{ display: "flex", flexWrap: "wrap", gap: 7, marginBottom: 18 }}>{tabs.map(([id, label]) => <button key={id} onClick={() => setActive(id)} style={{ ...S.input, width: "auto", cursor: "pointer", background: active === id ? "#2563EB" : "#050814" }}>{label}</button>)}</div>;

function ChamberTab({ type }) {
  const [v, setV] = useState({ unit: "MHz", source: "frequency" }); const [result, setResult] = useState(null); const [error, setError] = useState("");
  const input = (key, label) => <Field label={label}><input style={S.input} value={v[key] || ""} onChange={e => setV({ ...v, [key]: e.target.value })} inputMode="decimal" /></Field>;
  const calculate = () => { try { setError("");
    if (type === "geometry") { const N = chamberModesRectangular(n(v.a), n(v.b), n(v.d), frequencyToHz(n(v.f), v.unit)); setResult({ N }); }
    if (type === "volume") { const N = chamberModesEquivalent(n(v.volume), frequencyToHz(n(v.f), v.unit)); setResult({ N }); }
    if (type === "beat") { const mhz = chamberBeatFrequencyMHz(n(v.a), n(v.b)); setResult({ mhz, hz: mhz * 1e6 }); }
    if (type === "power") setResult(chamberKPower({ frequencyHz: v.source === "frequency" ? frequencyToHz(n(v.f), v.unit) : null, wavelength: v.source === "wavelength" ? n(v.lambda) : null, receivedMax: n(v.pr), incident: n(v.pi) }));
    if (type === "field") setResult(chamberKField(n(v.ex), n(v.ey), n(v.ez), n(v.pi)));
  } catch (e) { setResult(null); setError(e.message); } };
  return <>{type === "geometry" && <Grid>{input("a", "Длина a, м")}{input("b", "Ширина b, м")}{input("d", "Высота d, м")}{input("f", "Частота")}<Field label="Единица"><select style={S.input} value={v.unit} onChange={e => setV({...v,unit:e.target.value})}>{["Hz","kHz","MHz","GHz"].map(x=><option key={x}>{x}</option>)}</select></Field></Grid>}
    {type === "volume" && <Grid>{input("volume", "Эквивалентный объём Vэкв, м³")}{input("f", "Частота")}<Field label="Единица"><select style={S.input} value={v.unit} onChange={e => setV({...v,unit:e.target.value})}>{["Hz","kHz","MHz","GHz"].map(x=><option key={x}>{x}</option>)}</select></Field></Grid>}
    {type === "beat" && <Grid>{input("a", "a, м")}{input("b", "b, м")}</Grid>}
    {type === "power" && <><Tabs tabs={[["frequency","По частоте"],["wavelength","По λ"]]} active={v.source} setActive={source=>setV({...v,source})}/><Grid>{v.source === "frequency" ? <>{input("f", "Частота")}<Field label="Единица"><select style={S.input} value={v.unit} onChange={e=>setV({...v,unit:e.target.value})}>{["Hz","kHz","MHz","GHz"].map(x=><option key={x}>{x}</option>)}</select></Field></> : input("lambda", "Длина волны λ, м")}{input("pr", "Pприём max, Вт")}{input("pi", "Pпад, Вт")}</Grid></>}
    {type === "field" && <Grid>{input("ex", "Ex max, В/м")}{input("ey", "Ey max, В/м")}{input("ez", "Ez max, В/м")}{input("pi", "Pпад, Вт")}</Grid>}
    <Actions calculate={calculate} clear={()=>{setV({unit:"MHz",source:"frequency"});setResult(null);setError("");}}/>{error && <Result>Ошибка: {error}</Result>}
    {result && <Result>{result.N != null && <>N = <b>{pretty(result.N)}</b><br/>{result.N > 60 ? "Условие N > 60 выполнено" : "Для данной частоты условие N > 60 не выполнено"}</>}{result.mhz != null && <>Расчётная частота камеры: <b>{pretty(result.mhz)} MHz</b> ({pretty(result.hz)} Hz)</>}{result.wavelength != null && <>λ = <b>{pretty(result.wavelength)} м</b><br/>K = <b>{pretty(result.k)}</b></>}{result.rmsComponent != null && <>Среднеквадратичная составляющая поля = <b>{pretty(result.rmsComponent)} В/м</b><br/>K = <b>{pretty(result.k)}</b></>}</Result>}</>;
}

export function ReverberationChamberCalc() { const [tab,setTab]=useState("geometry"); return <div><h2>Реверберационная камера</h2><p style={{color:"#94A3B8"}}>Геометрия и коэффициенты камеры по зависимостям из предоставленного файла.</p><div style={S.card}><Tabs tabs={[["geometry","Геометрия камеры"],["volume","Эквивалентный объём"],["beat","Частота камеры"],["power","K — по мощности"],["field","K — по полю"]]} active={tab} setActive={setTab}/><ChamberTab type={tab}/></div></div>; }

export function AntennaEngineeringCalc() { const [tab,setTab]=useState("receive"); const [v,setV]=useState({unit:"MHz",voltageUnit:"linear",source:"frequency"}); const [r,setR]=useState(null); const [error,setError]=useState(""); const input=(k,l)=><Field label={l}><input style={S.input} value={v[k]||""} onChange={e=>setV({...v,[k]:e.target.value})}/></Field>; const calc=()=>{try{setError(""); if(tab==="receive")setR(antennaFactorReceive({frequencyHz:frequencyToHz(n(v.f),v.unit),u1:n(v.u1),u2:n(v.u2),distance:n(v.distance),unit:v.voltageUnit}));if(tab==="transmit")setR({aft:antennaFactorTransmit({af:n(v.af),distance:n(v.distance),frequencyHz:v.source==="frequency"?frequencyToHz(n(v.f),v.unit):null,wavelength:v.source==="wavelength"?n(v.lambda):null})});if(tab==="spacing")setR({b:antennaPositionStep(n(v.a),n(v.positions))});if(tab==="field")setR({field:fieldFromMeasuredVoltage(n(v.measured),n(v.af))});}catch(e){setR(null);setError(e.message)}}; return <div><h2>Antenna Factor / Antenna & Chamber</h2><div style={S.card}><Tabs tabs={[["receive","Приём"],["transmit","Передача"],["spacing","Расстояние B"],["field","Поле по напряжению"]]} active={tab} setActive={x=>{setTab(x);setR(null)}}/>{tab==="receive"&&<Grid>{input("f","Частота")}<Field label="Единица частоты"><select style={S.input} value={v.unit} onChange={e=>setV({...v,unit:e.target.value})}>{["Hz","kHz","MHz","GHz"].map(x=><option key={x}>{x}</option>)}</select></Field>{input("u1","U1")}{input("u2","U2")}{input("distance","Расстояние r, м")}<Field label="Единицы U1/U2"><select style={S.input} value={v.voltageUnit} onChange={e=>setV({...v,voltageUnit:e.target.value})}><option value="linear">Линейные, В</option><option value="db">dB / dBµV</option></select></Field></Grid>}{tab==="transmit"&&<><Tabs tabs={[["frequency","По частоте"],["wavelength","По λ"]]} active={v.source} setActive={source=>setV({...v,source})}/><Grid>{input("af","AF, dB/m")}{input("distance","r, м")}{v.source==="frequency"?input("f","Частота (MHz)"):input("lambda","λ, м")}</Grid></>}{tab==="spacing"&&<Grid>{input("a","A, м")}{input("positions","N, позиций")}</Grid>}{tab==="field"&&<Grid>{input("measured","Измеренное напряжение, dBµV")}{input("af","Антенный фактор, dB/m")}</Grid>}<Actions calculate={calc} clear={()=>{setV({unit:"MHz",voltageUnit:"linear",source:"frequency"});setR(null);setError("")}}/>{error&&<Result>Ошибка: {error}</Result>}{r&&<Result>{r.deltaU!=null&&<>ΔU = {pretty(r.deltaU)}<br/>K1 = {pretty(r.k1)}<br/>λ = {pretty(r.wavelength)} м<br/>G = {pretty(r.gain)}<br/>AF = <b>{pretty(r.af)} dB/m</b></>}{r.aft!=null&&<>AFT(f) = <b>{pretty(r.aft)} dB/m</b></>}{r.b!=null&&<>B = <b>{pretty(r.b)} м</b></>}{r.field!=null&&<>Напряжённость поля = <b>{pretty(r.field)} dBµV/m</b></>}</Result>}</div></div>; }

export function ShieldingCalc(){const[v,setV]=useState({});const[r,setR]=useState(null);const[error,setError]=useState("");return <div><h2>Эффективность экранирования корпуса</h2><p style={{color:"#94A3B8"}}>Разность уровня без экранирования и уровня при установленном корпусе.</p><div style={S.card}><Grid><Field label="Уровень без корпуса, dB"><input style={S.input} value={v.a||""} onChange={e=>setV({...v,a:e.target.value})}/></Field><Field label="Уровень с корпусом, dB"><input style={S.input} value={v.b||""} onChange={e=>setV({...v,b:e.target.value})}/></Field></Grid><Actions calculate={()=>{try{setR(shieldingEffectiveness(n(v.a),n(v.b)));setError("")}catch(e){setError(e.message)}}} clear={()=>{setV({});setR(null);setError("")}}/>{error&&<Result>Ошибка: {error}</Result>}{r!=null&&<Result>Эффективность экранирования: <b>{pretty(r)} dB</b></Result>}</div></div>}

function LimitChart({curve,measured=[]}){const pts=sampleLimit(curve);const all=[...pts,...measured];const minX=Math.log10(Math.min(...all.map(p=>p[0]))),maxX=Math.log10(Math.max(...all.map(p=>p[0])));const minY=Math.min(...all.map(p=>p[1]))-3,maxY=Math.max(...all.map(p=>p[1]))+3;const x=f=>40+(Math.log10(f)-minX)/(maxX-minX||1)*540,y=v=>15+(maxY-v)/(maxY-minY||1)*210;return <svg viewBox="0 0 600 260" style={{width:"100%",maxHeight:360}} aria-label="График нормативной линии PASS FAIL"><path d={pts.map((p,i)=>`${i?'L':'M'}${x(p[0])},${y(p[1])}`).join(' ')} fill="none" stroke="#60A5FA" strokeWidth="2"/>{measured.map(([f,v],i)=>{const pass=v<=evaluateLimit(curve,f);return <circle key={i} cx={x(f)} cy={y(v)} r="5" fill={pass?"#10B981":"#EF4444"}/>})}<text x="40" y="250" fill="#94A3B8" fontSize="11">Частота, MHz (log)</text></svg>}
export function NormativeLimitsCalc(){const[id,setId]=useState("voltage");const[f,setF]=useState("");const[level,setLevel]=useState("");const curve=EMC_LIMITS[id];const limit=evaluateLimit(curve,n(f));const measured=Number.isFinite(n(f))&&Number.isFinite(n(level))&&f!==""&&level!==""?[[n(f),n(level)]]:[];return <div><h2>Нормативные лимитные линии</h2><p style={{color:"#94A3B8"}}>Частотно-зависимые пределы из предоставленного файла; за диапазонами значения не экстраполируются.</p><div style={S.card}><Field label="Кривая"><select style={S.input} value={id} onChange={e=>setId(e.target.value)}>{Object.entries(EMC_LIMITS).map(([k,c])=><option key={k} value={k}>{c.name}</option>)}</select></Field><Grid><Field label="Частота, MHz"><input style={S.input} value={f} onChange={e=>setF(e.target.value)}/></Field><Field label={`Измеренный уровень, ${curve.unit}`}><input style={S.input} value={level} onChange={e=>setLevel(e.target.value)}/></Field></Grid><Result>{limit==null?"Для данной частоты нормативный предел не задан.":<>Предел: <b>{pretty(limit)} {curve.unit}</b>{measured.length>0&&<> · {n(level)<=limit?<b style={{color:'#10B981'}}>PASS</b>:<b style={{color:'#EF4444'}}>FAIL</b>}</>}</>}</Result><LimitChart curve={curve} measured={measured}/><small style={{color:"#94A3B8"}}>{curve.note} Источник: {curve.source}</small></div></div>}
