import { createScenario, normalizeNumber } from "../engine.mjs";
import { calculateControlDeflection, checkFieldUniformity, checkLaboratoryConditions, classifyMagneticEffect, SECTION_15_LIMITS } from "../section15Calculations.mjs";

const numeric = (message, { min = -Infinity, required = true } = {}) => value => {
  if (!required && String(value ?? "").trim() === "") return null;
  const n = normalizeNumber(value); return !Number.isFinite(n) || n < min ? message : null;
};
const condition = (id, label, hint) => ({ id, label, type: "text", inputMode: "decimal", hint, validate: numeric("Введите конечное числовое значение"), status: inputs => checkLaboratoryConditions(inputs).checks[id] ? "✓ соответствует" : "⚠ вне стандартных условий" });
const dc = inputs => { try { return calculateControlDeflection(inputs.h); } catch { return null; } };
const fmt = (value, digits = 2) => value == null ? "—" : value.toLocaleString("ru-RU", { maximumFractionDigits: digits, minimumFractionDigits: digits });

export const section15MagneticEffect = createScenario({
  id: "section-15-magnetic-effect-v1", title: "15 — Магнитное воздействие", standard: "RTCA DO-160G", section: "Section 15 — Magnetic Effect",
  description: "Определение минимального расстояния между испытуемым оборудованием и магнитным компасом или эквивалентным магнитным датчиком.",
  stageOrder: ["conditions", "equipment", "preparation", "diagram", "measurementSetup", "procedure", "result"],
  equipmentRequirements: [
    { id: "deflectionInstrument", type: "Компас / буссоль", aliases: ["Магнитный датчик", "Другое"], title: "Средство определения магнитного отклонения", optional: false, typeChoices: ["Компас / буссоль", "Магнитный датчик / эквивалентное средство"] },
    { id: "magnetometer", type: "Магнитометр", aliases: ["Другое"], title: "Магнитометр (если H не известно заранее)", optional: true },
  ],
  stages: {
    conditions: { fields: [
      condition("temperature", "Температура, °C", "+15…+35 °C"), condition("humidity", "Относительная влажность, %", "не более 85 %"), condition("pressure", "Атмосферное давление, кПа", "84…107 кПа"),
      { id: "h", label: "Горизонтальная составляющая окружающего магнитного поля H, А/м", inputMode: "decimal", hint: "Опорный диапазон: 12,96…15,84 А/м", validate: numeric("H должно быть конечным числом больше 0", { min: Number.MIN_VALUE }) },
    ], notices: [{ tone: "warning", visibleWhen: inputs => !checkLaboratoryConditions(inputs).ok, text: "Фактические условия испытания выходят за стандартный диапазон. Зафиксируйте их в результатах испытания." }], derived: [{ label: "Измеренное поле H", value: i => Number.isFinite(normalizeNumber(i.h)) ? `${i.h} А/м` : "—" }, { label: "Контрольное отклонение Dc", value: i => dc(i) == null ? "—" : `${fmt(dc(i))}°` }, { value: i => { const h = normalizeNumber(i.h); return h >= SECTION_15_LIMITS.hMin && h <= SECTION_15_LIMITS.hMax ? "✓ Окружающее магнитное поле находится в опорном диапазоне." : dc(i) == null ? "" : "⚠ Окружающее магнитное поле отличается от опорного. Toolkit рассчитал скорректированное значение Dc." } }] },
    equipment: { fields: [{ id: "eutName", label: "Наименование испытуемого оборудования" }, { id: "eutModel", label: "Обозначение / модель" }, { id: "eutMode", label: "Режим работы" }, { id: "eutNote", label: "Примечание" }] },
    preparation: { heading: "Подготовьте испытуемое оборудование", actions: [
      ["eutConnected", "ИО подключено", "Подключите ИО в конфигурации, соответствующей испытанию."], ["harnessReady", "Кабельный жгут подготовлен", "Используйте кабельный жгут испытательной конфигурации. Кабели ИО и удлинённые цепи питания соберите в общий жгут."], ["magneticObjectsRemoved", "Посторонние магнитные предметы удалены", "Убедитесь, что рядом с компасом или датчиком нет посторонних ферромагнитных предметов."], ["nonMagneticSupports", "Используются немагнитные опоры", "Установите ИО и измерительное средство на немагнитные опоры."],
    ].map(([id, title, instruction]) => ({ id, title, instruction, checkboxLabel: title })) },
    diagram: { diagram: { title: "Схема установки", image: "/section15-setup.svg", alt: "Схема испытания на магнитное воздействие", description: "D — расстояние от оси магнитного элемента компаса/датчика до ближайшей части испытуемого оборудования.", enlargeLabel: "Открыть схему крупнее" }, photos: true },
    measurementSetup: { heading: "Определите окружающее магнитное поле", actions: [{ id: "removeEut", title: "Шаг 1. Уберите ИО из зоны измерения", instruction: "Освободите предполагаемую траекторию измерения." }, { id: "measureH", title: "Шаг 2. Определите H", instruction: "Определите горизонтальную составляющую окружающего магнитного поля. Используется значение, введённое на этапе условий." }], derived: [{ label: "H", value: i => `${i.h || "—"} А/м` }, { label: "Dc", value: i => dc(i) == null ? "—" : `${fmt(dc(i))}°` }], fields: [{ id: "method", type: "radio", label: "Метод проведения испытания", options: [{ value: "eut", label: "Перемещается ИО, компас/датчик остаётся неподвижным" }, { value: "sensor", label: "Перемещается компас/датчик относительно ИО" }] }, { id: "uniformity", label: "Максимальное изменение показаний, °", hint: "Критерий: не более ±0,5°", inputMode: "decimal", visibleWhen: i => i.method === "sensor", validate: numeric("Введите конечное числовое значение"), status: i => checkFieldUniformity(i.uniformity).invalid ? "" : checkFieldUniformity(i.uniformity).ok ? "✓ Однородность поля достаточна." : "⚠ Изменение поля вдоль траектории превышает ±0,5°. Проверьте место проведения испытания и наличие магнитных объектов." }], notices: [{ visibleWhen: i => i.method === "sensor", text: "Уберите ИО и перемещайте компас/датчик по предполагаемой траектории измерения. Проверьте изменение показаний относительно исходного положения." }] },
    procedure: { actions: [{ id: "maximumModeFound", title: "Шаг 1. Включите испытуемое оборудование", instruction: "Переведите ИО в нормальный рабочий режим. Проверьте устойчивые режимы и определите режим максимального влияния на компас/датчик.", checkboxLabel: "Режим максимального воздействия найден" }, { id: "maximumPositionFound", title: "Шаг 2. Найдите положение максимального воздействия", instruction: "Изменяйте положение и ориентацию ИО и найдите максимальное магнитное отклонение.", explanation: "Сохраняйте испытательную конфигурацию и положение кабельного жгута согласно схеме.", checkboxLabel: "Положение максимального воздействия найдено" }, { id: "findDistance", title: "Шаг 3. Найдите расстояние D", instruction: "Изменяйте расстояние до момента, когда отклонение станет равным Dc. Измерьте D от оси магнитного элемента до ближайшей части ИО." }], derived: [{ label: "Контрольное отклонение", value: i => dc(i) == null ? "Dc = —" : `Dc = ${fmt(dc(i))}°`, prominent: true }], fields: [{ id: "maximumMode", label: "Режим максимального воздействия" }, { id: "reachesDc", type: "radio", label: "Достигается ли контрольное отклонение Dc при минимально возможном расстоянии?", options: [{ value: "yes", label: "Да" }, { value: "no", label: "Нет" }] }, { id: "distance", label: "Расстояние D, м", inputMode: "decimal", visibleWhen: i => i.reachesDc === "yes", validate: numeric("D должно быть конечным неотрицательным числом", { min: 0 }) }, { id: "maximumDeflection", label: "Фактическое максимальное отклонение, ° (необязательно)", inputMode: "decimal", validate: numeric("Введите конечное числовое значение", { required: false }) }], notices: [{ tone: "info", visibleWhen: i => i.reachesDc === "no", text: "Даже при непосредственном расположении ИО контрольное отклонение Dc не достигнуто. Для классификации D принято равным 0." }], photos: true },
    result: { result: inputs => { const reaches = inputs.reachesDc !== "no"; let category = "—", distance = reaches ? normalizeNumber(inputs.distance) : 0; try { category = classifyMagneticEffect(distance, reaches); } catch {} return { category, distance: Number.isFinite(distance) ? distance : null, dc: dc(inputs), conditions: checkLaboratoryConditions(inputs), uniformity: inputs.method === "sensor" ? checkFieldUniformity(inputs.uniformity) : null }; } },
  },
});
