import { createScenario, normalizeNumber } from "../engine.mjs";
import { calculateControlDeflection, checkFieldUniformity, checkLaboratoryConditions, getMagneticEffectResult, SECTION_15_LIMITS } from "../section15Calculations.mjs";

const numeric = (message, { min = -Infinity, required = true } = {}) => value => {
  if (!required && String(value ?? "").trim() === "") return null;
  const n = normalizeNumber(value); return !Number.isFinite(n) || n < min ? message : null;
};
const condition = (id, label, hint) => ({ id, label, type: "text", inputMode: "decimal", hint, validate: numeric("Введите конечное числовое значение"), status: inputs => checkLaboratoryConditions(inputs).checks[id] ? "✓ соответствует" : "⚠ вне стандартных условий" });
const dc = inputs => { try { return calculateControlDeflection(inputs.h); } catch { return null; } };
const fmt = (value, digits = 2) => value == null ? "—" : value.toLocaleString("ru-RU", { maximumFractionDigits: digits, minimumFractionDigits: digits });

export const section15MagneticEffect = createScenario({
  id: "section-15-magnetic-effect-v1", title: "15 — Магнитное воздействие", standard: "RTCA DO-160G", section: "Section 15 — Magnetic Effect",
  description: "Определение минимального расстояния между испытуемым изделием и магнитным компасом или эквивалентным магнитным датчиком.",
  showStageCompletion: false,
  stageOrder: ["conditions", "equipment", "preparation", "diagram", "measurementSetup", "procedure", "result"],
  equipmentRequirements: [
    { id: "deflectionInstrument", type: "Компас / буссоль", aliases: ["Магнитный датчик", "Другое"], title: "Средство определения магнитного отклонения", optional: false, typeChoices: ["Компас / буссоль", "Магнитный датчик / эквивалентное средство"] },
    { id: "magnetometer", type: "Магнитометр", aliases: ["Другое"], title: "Магнитометр (если H не известно заранее)", optional: true },
  ],
  stages: {
    conditions: { derivedAfterFields: true, derivedHeading: "Расчёт для испытания", fields: [
      condition("temperature", "Температура, °C", "+15…+35 °C"), condition("humidity", "Относительная влажность, %", "не более 85 %"), condition("pressure", "Атмосферное давление, кПа", "84…107 кПа"),
      { id: "h", label: "Горизонтальная составляющая окружающего магнитного поля H, А/м", inputMode: "decimal", hint: "Опорный диапазон: 12,96…15,84 А/м", validate: numeric("H должно быть конечным числом больше 0", { min: Number.MIN_VALUE }) },
    ], notices: [{ tone: "warning", visibleWhen: inputs => !checkLaboratoryConditions(inputs).ok, text: "Фактические условия испытания выходят за стандартный диапазон. Зафиксируйте их в результатах испытания." }], derivedVisibleWhen: i => dc(i) != null, derived: [{ label: "Измеренное поле H", value: i => `${fmt(normalizeNumber(i.h), 1)} А/м` }, { label: "Контрольное отклонение Dc", value: i => `${fmt(dc(i))}°` }, { value: i => { const h = normalizeNumber(i.h); return h >= SECTION_15_LIMITS.hMin && h <= SECTION_15_LIMITS.hMax ? "✓ Окружающее магнитное поле находится в опорном диапазоне." : "⚠ Окружающее магнитное поле отличается от опорного. Контрольное отклонение Dc скорректировано автоматически." } }] },
    equipment: { fields: [{ id: "eutName", label: "Наименование изделия" }, { id: "eutModel", label: "Обозначение / модель" }, { id: "eutMode", label: "Режим работы изделия" }, { id: "eutNote", label: "Примечание" }] },
    preparation: { heading: "Подготовьте изделие", showActionCompletion: false, actions: [
      ["eutConnected", "1. Подключите изделие", "Подключите изделие в конфигурации, соответствующей испытанию."], ["harnessReady", "2. Подготовьте кабельный жгут", "Используйте жгут испытательной конфигурации. Кабели изделия и удлинённые цепи питания соберите в общий жгут."], ["magneticObjectsRemoved", "3. Уберите посторонние магнитные предметы", "Рядом с компасом или магнитным датчиком не должно быть посторонних ферромагнитных предметов, способных повлиять на результат."], ["nonMagneticSupports", "4. Используйте немагнитные опоры", "Установите изделие и измерительное средство на немагнитную поверхность / опоры."],
    ].map(([id, title, instruction]) => ({ id, title, instruction })) },
    diagram: { diagram: { title: "Схема установки", image: "/section15-setup.svg", alt: "Схема испытания на магнитное воздействие", description: "D — расстояние от оси магнитного элемента компаса/датчика до ближайшей части изделия.", enlargeLabel: "Открыть схему крупнее" }, photos: true },
    measurementSetup: { heading: "Определите окружающее магнитное поле", showActionCompletion: false, actions: [{ id: "removeEut", title: "Шаг 1. Уберите изделие из зоны измерения", instruction: "Освободите предполагаемую траекторию измерения." }, { id: "measureH", title: "Шаг 2. Определите H", instruction: "Определите горизонтальную составляющую окружающего магнитного поля. Используется значение, введённое на этапе условий." }], derived: [{ label: "H", value: i => `${i.h || "—"} А/м` }, { label: "Dc", value: i => dc(i) == null ? "—" : `${fmt(dc(i))}°` }], fields: [{ id: "method", type: "radio", label: "Метод проведения испытания", options: [{ value: "eut", label: "Перемещается изделие, компас/датчик остаётся неподвижным" }, { value: "sensor", label: "Перемещается компас/датчик относительно изделия" }] }, { id: "uniformity", label: "Максимальное изменение показаний, °", hint: "Критерий: не более ±0,5°", inputMode: "decimal", visibleWhen: i => i.method === "sensor", validate: numeric("Введите конечное числовое значение"), status: i => checkFieldUniformity(i.uniformity).invalid ? "" : checkFieldUniformity(i.uniformity).ok ? "✓ Однородность поля достаточна." : "⚠ Изменение поля вдоль траектории превышает ±0,5°. Проверьте место проведения испытания и наличие магнитных объектов." }], notices: [{ visibleWhen: i => i.method === "sensor", text: "Уберите изделие и перемещайте компас/датчик по предполагаемой траектории измерения. Проверьте изменение показаний относительно исходного положения." }] },
    procedure: { showActionCompletion: false, actions: [{ id: "maximumModeFound", title: "1. Включите изделие", instruction: "Переведите изделие в рабочий режим. Если у изделия несколько режимов, проверьте их и выберите тот, при котором отклонение компаса или датчика максимально." }, { id: "maximumPositionFound", title: "2. Найдите положение максимального воздействия", instruction: "Изменяйте положение и ориентацию изделия относительно компаса или датчика. Найдите положение, при котором отклонение максимально.", explanation: "Сохраняйте положение кабельного жгута согласно схеме." }, { id: "findDistance", title: "3. Найдите расстояние D", instruction: "Изменяйте расстояние между изделием и компасом/датчиком до момента, когда отклонение станет равным Dc. После этого измерьте расстояние от оси магнитного элемента компаса/датчика до ближайшей части изделия." }], derived: [{ label: "Контрольное отклонение", value: i => dc(i) == null ? "Dc = —" : `Dc = ${fmt(dc(i))}°`, prominent: true }], fields: [{ id: "maximumMode", label: "Режим максимального воздействия" }, { id: "reachesDc", type: "radio", label: "Достигается ли контрольное отклонение Dc при минимально возможном расстоянии?", options: [{ value: "yes", label: "Да" }, { value: "no", label: "Нет" }] }, { id: "distance", label: "Расстояние D, м", inputMode: "decimal", visibleWhen: i => i.reachesDc === "yes", validate: numeric("D должно быть конечным неотрицательным числом", { min: 0 }) }], measurementResult: inputs => inputs.reachesDc === "no" || inputs.reachesDc === "yes" ? getMagneticEffectResult(inputs) : null, photos: true },
    result: { title: "Итог", result: inputs => { const result = getMagneticEffectResult(inputs); return result && { ...result, conditions: checkLaboratoryConditions(inputs), uniformity: inputs.method === "sensor" ? checkFieldUniformity(inputs.uniformity) : null }; } },
  },
});
